import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Modern Sectional Sofa",
    price: 1299,
    originalPrice: 1599,
    description:
      "This contemporary sectional sofa combines comfort and style with its plush cushions and sleek design. Perfect for modern living rooms, it features high-quality fabric upholstery and a sturdy hardwood frame.",
    shortDescription: "Contemporary sectional with plush cushions",
    category: "Sofas",
    color: "Gray",
    size: "Large",
    material: "Fabric",
    image: "/images/modern-sectional-sofa.jpg",
    images: [
      "/images/modern-sectional-sofa.jpg",
      "/images/modern-sectional-sofa.jpg",
      "/images/modern-sectional-sofa.jpg",
    ],
    inStock: true,
    rating: 4.5,
    reviews: [
      {
        id: "1",
        author: "Sarah Johnson",
        rating: 5,
        comment: "Absolutely love this sofa! Very comfortable and looks great in our living room.",
        date: "2024-01-15",
      },
    ],
    specifications: {
      Dimensions: '108" W x 75" D x 35" H',
      Weight: "180 lbs",
      Material: "Premium fabric upholstery",
      Frame: "Hardwood construction",
      Warranty: "5 years",
    },
  },
  {
    id: "2",
    name: "Oak Dining Table",
    price: 899,
    description:
      "Handcrafted solid oak dining table that seats up to 6 people comfortably. Features a beautiful natural wood grain and durable finish that will last for generations.",
    shortDescription: "Solid oak table seats 6",
    category: "Dining",
    color: "Natural Oak",
    size: "Medium",
    material: "Wood",
    image: "/images/oak-dining-table.jpg",
    images: ["/images/oak-dining-table.jpg", "/images/oak-dining-table.jpg"],
    inStock: true,
    rating: 4.8,
    reviews: [
      {
        id: "2",
        author: "Mike Chen",
        rating: 5,
        comment: "Beautiful craftsmanship. The wood quality is exceptional.",
        date: "2024-01-10",
      },
    ],
    specifications: {
      Dimensions: '72" L x 36" W x 30" H',
      Weight: "120 lbs",
      Material: "Solid oak wood",
      Finish: "Natural oil finish",
      Seating: "Up to 6 people",
    },
  },
  {
    id: "3",
    name: "Ergonomic Office Chair",
    price: 449,
    originalPrice: 599,
    description:
      "Professional ergonomic office chair with lumbar support, adjustable height, and breathable mesh back. Designed for all-day comfort and productivity.",
    shortDescription: "Ergonomic chair with lumbar support",
    category: "Office",
    color: "Black",
    size: "Standard",
    material: "Mesh",
    image: "/images/office-chair.jpg",
    images: ["/images/office-chair.jpg", "/images/office-chair.jpg"],
    inStock: true,
    rating: 4.3,
    reviews: [
      {
        id: "3",
        author: "Lisa Wang",
        rating: 4,
        comment: "Great chair for long work days. Very supportive.",
        date: "2024-01-08",
      },
    ],
    specifications: {
      Dimensions: '26" W x 26" D x 40-44" H',
      Weight: "35 lbs",
      Material: "Breathable mesh",
      Adjustment: "Height, tilt, armrests",
      "Weight Capacity": "300 lbs",
    },
  },
  {
    id: "4",
    name: "King Size Platform Bed",
    price: 799,
    description:
      "Minimalist platform bed frame with built-in nightstands. Clean lines and modern design make it perfect for contemporary bedrooms.",
    shortDescription: "Platform bed with built-in nightstands",
    category: "Bedroom",
    color: "Walnut",
    size: "King",
    material: "Wood",
    image: "/images/platform-bed.jpg",
    images: ["/images/platform-bed.jpg", "/images/platform-bed.jpg"],
    inStock: true,
    rating: 4.6,
    reviews: [
      {
        id: "4",
        author: "David Brown",
        rating: 5,
        comment: "Love the built-in nightstands. Very sturdy construction.",
        date: "2024-01-05",
      },
    ],
    specifications: {
      Dimensions: '84" L x 80" W x 14" H',
      Weight: "150 lbs",
      Material: "Engineered wood",
      Finish: "Walnut veneer",
      Assembly: "Required",
    },
  },
  {
    id: "5",
    name: "Glass Coffee Table",
    price: 349,
    description:
      "Modern glass coffee table with chrome legs. The tempered glass top is both stylish and practical, perfect for contemporary living spaces.",
    shortDescription: "Modern glass table with chrome legs",
    category: "Tables",
    color: "Clear",
    size: "Medium",
    material: "Glass",
    image: "/images/glass-coffee-table.jpg",
    images: ["/images/glass-coffee-table.jpg"],
    inStock: false,
    rating: 4.2,
    reviews: [],
    specifications: {
      Dimensions: '48" L x 24" W x 16" H',
      Weight: "45 lbs",
      Material: "Tempered glass",
      Base: "Chrome steel",
      Thickness: "10mm glass",
    },
  },
  {
    id: "6",
    name: "Leather Recliner",
    price: 1099,
    description:
      "Luxurious leather recliner with power recline and USB charging ports. Premium top-grain leather and exceptional comfort for relaxation.",
    shortDescription: "Power recliner with USB charging",
    category: "Chairs",
    color: "Brown",
    size: "Large",
    material: "Leather",
    image: "/images/leather-recliner.jpg",
    images: ["/images/leather-recliner.jpg", "/images/leather-recliner.jpg"],
    inStock: true,
    rating: 4.7,
    reviews: [
      {
        id: "5",
        author: "Jennifer Lee",
        rating: 5,
        comment: "The most comfortable chair I've ever owned. Love the USB ports!",
        date: "2024-01-03",
      },
    ],
    specifications: {
      Dimensions: '32" W x 38" D x 42" H',
      Weight: "95 lbs",
      Material: "Top-grain leather",
      Features: "Power recline, USB ports",
      Warranty: "3 years",
    },
  },
]

export const categories = ["All", "Sofas", "Dining", "Office", "Bedroom", "Tables", "Chairs"]
export const colors = ["All", "Gray", "Natural Oak", "Black", "Walnut", "Clear", "Brown"]
export const materials = ["All", "Fabric", "Wood", "Mesh", "Glass", "Leather"]
export const sizes = ["All", "Small", "Medium", "Large", "King", "Standard"]
